import { NgModule } from '@angular/core';

import {
    DxButtonModule,
    DxDataGridModule,
    DxDateBoxModule,
    DxFormModule,
    DxLookupModule,
    DxNumberBoxModule,
    DxPopupModule,
    DxTextBoxModule,
    DxLoadPanelModule,
    DxBoxModule,
    DxCheckBoxModule,
    DxToolbarModule,
    DxValidatorModule,
    DxValidationSummaryModule,
    DxTabPanelModule,
    DxFileUploaderModule,
    DxSelectBoxModule,
    DxTextAreaModule,
    DxScrollViewModule,
    DxSwitchModule,
    DxValidationGroupModule,
    DxListModule,
    DxResizableModule,
    DxChartModule,
    DxRadioGroupModule
} from 'devextreme-angular';

@NgModule({
    declarations: [],
    imports: [
        DxButtonModule,
        DxDataGridModule,
        DxTextBoxModule,
        DxNumberBoxModule,
        DxDateBoxModule,
        DxLookupModule,
        DxPopupModule,
        DxFormModule,
        DxLoadPanelModule,
        DxBoxModule,
        DxCheckBoxModule,
        DxToolbarModule,
        DxValidatorModule,
        DxValidationSummaryModule,
        DxTabPanelModule,
        DxFileUploaderModule,
        DxSelectBoxModule,
        DxTextAreaModule,
        DxScrollViewModule,
        DxSwitchModule,
        DxValidationGroupModule ,
        DxListModule,
        DxResizableModule,
        DxChartModule,
        DxRadioGroupModule
    ],
    exports: [
        DxButtonModule,
        DxListModule,
        DxDataGridModule,
        DxTextBoxModule,
        DxNumberBoxModule,
        DxDateBoxModule,
        DxLookupModule,
        DxPopupModule,
        DxFormModule,
        DxLoadPanelModule,
        DxBoxModule,
        DxCheckBoxModule,
        DxToolbarModule,
        DxValidatorModule,
        DxValidationSummaryModule,
        DxTabPanelModule,
        DxFileUploaderModule,
        DxSelectBoxModule,
        DxTextAreaModule,
        DxScrollViewModule,
        DxSwitchModule,
        DxValidationGroupModule,
        DxResizableModule,
        DxChartModule,
        DxRadioGroupModule
    ],
    providers: []
})
export class DevXComponentsModule {
}